param(
    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[a-z0-9]{20}$')]
    [string]$ProjectRef
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$linkedRefFile = Join-Path $repoRoot 'supabase/.temp/project-ref'

if (-not (Test-Path -LiteralPath $linkedRefFile)) {
    throw 'This repository is not linked to a Supabase project. Run supabase link first.'
}

$linkedRef = (Get-Content -LiteralPath $linkedRefFile -Raw).Trim()
if ($linkedRef -ne $ProjectRef) {
    throw "Linked project ref ($linkedRef) does not match requested project ref ($ProjectRef)."
}

$secureSecret = Read-Host 'Paste the same WEBHOOK_SECRET saved in this project Edge Function Secrets' -AsSecureString
$secretPointer = [IntPtr]::Zero
$temporarySql = $null

try {
    $secretPointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureSecret)
    $webhookSecret = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($secretPointer)
    if ($webhookSecret -notmatch '^[A-Za-z0-9+/]{43}=$') {
        throw 'Expected the 32-byte Base64 WEBHOOK_SECRET generated by the documented PowerShell command.'
    }

    $secretSqlValue = $webhookSecret.Replace("'", "''")
    $functionUrl = "https://$ProjectRef.supabase.co/functions/v1/notify-submitter"
    $urlSqlValue = $functionUrl.Replace("'", "''")

    $sql = @'
do $$
declare
  secret_id uuid;
  url_id uuid;
begin
  select id into secret_id
  from vault.secrets
  where name = 'feedbackport_notify_submitter_secret'
  limit 1;

  if secret_id is null then
    perform vault.create_secret('__WEBHOOK_SECRET__', 'feedbackport_notify_submitter_secret', 'Shared secret for FeedbackPort database webhooks');
  else
    perform vault.update_secret(secret_id, '__WEBHOOK_SECRET__', 'feedbackport_notify_submitter_secret', 'Shared secret for FeedbackPort database webhooks');
  end if;

  select id into url_id
  from vault.secrets
  where name = 'feedbackport_notify_submitter_url'
  limit 1;

  if url_id is null then
    perform vault.create_secret('__FUNCTION_URL__', 'feedbackport_notify_submitter_url', 'Project-specific notify-submitter Edge Function URL');
  else
    perform vault.update_secret(url_id, '__FUNCTION_URL__', 'feedbackport_notify_submitter_url', 'Project-specific notify-submitter Edge Function URL');
  end if;
end;
$$;
'@
    $sql = $sql.Replace('__WEBHOOK_SECRET__', $secretSqlValue).Replace('__FUNCTION_URL__', $urlSqlValue)

    $temporarySql = Join-Path ([IO.Path]::GetTempPath()) ("feedbackport-webhooks-$([Guid]::NewGuid().ToString('N')).sql")
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [IO.File]::WriteAllText($temporarySql, $sql, $utf8NoBom)

    # Limit the short-lived SQL file to the current Windows user.
    $acl = Get-Acl -LiteralPath $temporarySql
    $acl.SetAccessRuleProtection($true, $false)
    $currentSid = [Security.Principal.WindowsIdentity]::GetCurrent().User
    $rule = New-Object Security.AccessControl.FileSystemAccessRule($currentSid, 'FullControl', 'Allow')
    $acl.SetAccessRule($rule)
    Set-Acl -Path $temporarySql -AclObject $acl

    Push-Location $repoRoot
    try {
        & corepack pnpm dlx supabase db query --linked --file $temporarySql
        if ($LASTEXITCODE -ne 0) { throw 'Could not store webhook configuration in Supabase Vault.' }

        & corepack pnpm dlx supabase db push --linked --yes
        if ($LASTEXITCODE -ne 0) { throw 'Could not apply the repeatable webhook migration.' }

        $verificationSql = "select jsonb_build_object('pg_net', exists(select 1 from pg_extension where extname = 'pg_net'), 'reply_trigger', exists(select 1 from pg_trigger where tgname = 'notify_submitter_reply_insert' and not tgisinternal), 'status_trigger', exists(select 1 from pg_trigger where tgname = 'notify_submitter_feedback_status_update' and not tgisinternal), 'secret_configured', exists(select 1 from vault.decrypted_secrets where name = 'feedbackport_notify_submitter_secret'), 'url_configured', exists(select 1 from vault.decrypted_secrets where name = 'feedbackport_notify_submitter_url')) as webhook_status;"
        & corepack pnpm dlx supabase db query --linked $verificationSql
        if ($LASTEXITCODE -ne 0) { throw 'Webhook verification query failed.' }
    } finally {
        Pop-Location
    }

    Write-Output 'Supabase Database Webhooks are configured. The secret value was not printed.'
} finally {
    if ($secretPointer -ne [IntPtr]::Zero) {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($secretPointer)
    }
    if ($secureSecret) { $secureSecret.Dispose() }
    Remove-Variable webhookSecret, secretSqlValue, sql -ErrorAction SilentlyContinue
    if ($temporarySql -and (Test-Path -LiteralPath $temporarySql)) {
        Remove-Item -LiteralPath $temporarySql -Force
    }
}
