export type Locale = "en" | "zh";

export function resolveLocale(acceptLanguage: string | null | undefined): Locale {
  return acceptLanguage?.toLowerCase().split(",")[0]?.trim().startsWith("zh") ? "zh" : "en";
}

export const UI_COPY = {
  en: {
    homeEyebrow: "Feedback for independent products",
    homeTitle: "A clear place for every product’s feedback.",
    homeDescription: "Collect ideas, see what users care about, and follow up across your products from one workspace.",
    homeBoard: "View the feedback board",
    adminSignIn: "Admin sign in",
    homeRoadmap: "See the project roadmap in",
    homeRoadmapSuffix: ", including the Phase 0 checklist.",
    boardTitle: "Feedback for",
    boardIntro: "Share an idea or vote for one you’d like to see. Search below before submitting a new one.",
    browseIdeas: "Browse ideas",
    shareIdea: "Share an idea",
    searchIdeas: "Search ideas",
    sortBy: "Sort by",
    mostVotes: "Most votes",
    voteSingular: "vote",
    votePlural: "votes",
    newest: "Newest",
    filterStatus: "Filter by status",
    allStatuses: "All statuses",
    loading: "Loading…",
    noIdeas: "No ideas yet. Be the first to share one.",
    noIdeasMatch: "No ideas match your search or filters.",
    ideaTitle: "What would you like to see?",
    ideaDetails: "Add any context that would help us understand the idea (optional)",
    yourEmail: "Your email",
    submitEmailHelp: "Your email lets the team follow up about this idea. It isn’t shown on the public board.",
    voteEmailHelp: "Used to prevent duplicate votes. It isn’t shown on the public board.",
    turnstileMissing: "Feedback can’t be submitted right now. Please try again later.",
    submitFailed: "We couldn’t send your idea. Check your connection and try again.",
    ideaShared: "Thanks — your idea has been shared.",
    submitting: "Sending…",
    submitIdea: "Share idea",
    vote: "Vote",
    voted: "Voted",
    alreadyVoted: "Already voted",
    voteFailed: "We couldn’t record your vote. Please try again.",
    voteSending: "Verifying…",
    confirmVote: "Confirm vote",
    cancel: "Cancel",
    backToBoard: "← Back to feedback",
    feedbackNotFound: "Idea not found.",
    replies: "Replies",
    noReplies: "No replies yet.",
    teamReply: "FeedbackPort team",
    noBoardProduct: "This board isn’t linked to a product. Open the board URL configured for your product.",
    adminBrand: "FeedbackPort",
    products: "Products",
    allFeedback: "All feedback",
    addProduct: "Add product",
    signOut: "Sign out",
    backToProducts: "← Back to products",
    workspace: "Workspace",
    workspaceInbox: "Feedback across products",
    productsHelper: "Choose a product to review its feedback.",
    allFeedbackHelper: "Review and reply to feedback across your products.",
    noProducts: "No products yet. Add a product to create its feedback board.",
    openCount: "open",
    totalCount: "total",
    latest: "Latest:",
    filterProduct: "Filter by product",
    productSlug: "Product slug",
    noFeedback: "No feedback matches these filters.",
    changeStatus: "Change status for",
    writeReply: "Write a reply…",
    reply: "Reply",
    addProductTitle: "Add a product",
    addProductHelper: "Create a dedicated feedback board for a product.",
    boardUrlSlug: "Board URL slug",
    slugPlaceholder: "e.g. cardwhisper",
    slugHelper: "Used in the public board URL. Use lowercase letters, numbers, and hyphens.",
    productName: "Product name",
    brandColor: "Brand color",
    slugExists: "That slug is already in use.",
    createFailed: "Couldn’t create the product. Try again.",
    creating: "Creating…",
    createProduct: "Create product",
    signInHelper: "We’ll email you a one-time sign-in link.",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    signInSent: "A sign-in link was sent to",
    signInSentSuffix: ". Check your inbox to continue.",
    sendSignInLink: "Send sign-in link",
    sending: "Sending…",
    signInFailed: "Couldn’t send the link. Make sure this email is set up as an administrator.",
    statusOpen: "Open",
    statusPlanned: "Planned",
    statusInProgress: "In progress",
    statusDone: "Done",
    statusDeclined: "Not planned",
  },
  zh: {
    homeEyebrow: "独立产品的用户反馈",
    homeTitle: "让每个产品的用户反馈，都有清晰去处。",
    homeDescription: "集中收集想法、了解用户关注点，并在一个工作区跟进多个产品的反馈。",
    homeBoard: "查看反馈面板",
    adminSignIn: "管理员登录",
    homeRoadmap: "查看项目路线图：",
    homeRoadmapSuffix: "（含 Phase 0 检查清单）",
    boardTitle: "用户反馈：",
    boardIntro: "分享一个想法，或为你希望实现的想法投票。提交之前，可以先搜索已有想法。",
    browseIdeas: "浏览想法",
    shareIdea: "分享想法",
    searchIdeas: "搜索想法",
    sortBy: "排序方式",
    mostVotes: "投票最多",
    voteSingular: "票",
    votePlural: "票",
    newest: "最新",
    filterStatus: "按状态筛选",
    allStatuses: "全部状态",
    loading: "正在加载…",
    noIdeas: "还没有想法，来分享第一个吧。",
    noIdeasMatch: "没有符合搜索或筛选条件的想法。",
    ideaTitle: "你希望产品增加或改进什么？",
    ideaDetails: "补充一些背景，帮助我们理解这个想法（选填）",
    yourEmail: "你的邮箱",
    submitEmailHelp: "团队会通过邮箱跟进这个想法；邮箱不会显示在公开面板上。",
    voteEmailHelp: "用于避免重复投票，不会显示在公开面板上。",
    turnstileMissing: "暂时无法提交想法，请稍后再试。",
    submitFailed: "想法提交失败，请检查网络后重试。",
    ideaShared: "感谢分享，想法已提交。",
    submitting: "正在提交…",
    submitIdea: "提交想法",
    vote: "投票",
    voted: "已投票",
    alreadyVoted: "已投过票",
    voteFailed: "投票未能提交，请重试。",
    voteSending: "正在验证…",
    confirmVote: "确认投票",
    cancel: "取消",
    backToBoard: "← 返回反馈列表",
    feedbackNotFound: "没有找到这个想法。",
    replies: "回复",
    noReplies: "还没有回复。",
    teamReply: "FeedbackPort 团队",
    noBoardProduct: "这个面板尚未关联产品，请打开为你的产品配置的面板网址。",
    adminBrand: "FeedbackPort",
    products: "产品",
    allFeedback: "全部反馈",
    addProduct: "新增产品",
    signOut: "退出登录",
    backToProducts: "← 返回产品列表",
    workspace: "工作区",
    workspaceInbox: "跨产品反馈",
    productsHelper: "选择一个产品，查看并跟进它的反馈。",
    allFeedbackHelper: "集中查看并回复所有产品的反馈。",
    noProducts: "还没有产品。新增产品即可创建对应的反馈面板。",
    openCount: "待处理",
    totalCount: "条反馈",
    latest: "最新：",
    filterProduct: "按产品筛选",
    productSlug: "产品标识（slug）",
    noFeedback: "没有符合条件的反馈。",
    changeStatus: "更改状态：",
    writeReply: "写一条回复…",
    reply: "回复",
    addProductTitle: "新增产品",
    addProductHelper: "为产品创建独立的反馈面板。",
    boardUrlSlug: "面板网址标识（slug）",
    slugPlaceholder: "例如 cardwhisper",
    slugHelper: "用于公开面板网址，只能使用小写字母、数字和连字符。",
    productName: "产品名称",
    brandColor: "品牌色",
    slugExists: "这个标识已被使用。",
    createFailed: "产品创建失败，请重试。",
    creating: "正在创建…",
    createProduct: "创建产品",
    signInHelper: "我们会向管理员邮箱发送一次性登录链接。",
    emailLabel: "邮箱",
    emailPlaceholder: "you@example.com",
    signInSent: "登录链接已发送至",
    signInSentSuffix: "，请查看邮箱并点击链接继续。",
    sendSignInLink: "发送登录链接",
    sending: "正在发送…",
    signInFailed: "登录链接发送失败，请确认该邮箱已设置为管理员账号。",
    statusOpen: "待处理",
    statusPlanned: "已计划",
    statusInProgress: "进行中",
    statusDone: "已完成",
    statusDeclined: "暂不计划",
  },
} as const;

export type UiCopy = (typeof UI_COPY)[Locale];
